// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/app/feature/forget_password/presentation/reset_password/view_model/reset_password_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/app/config/base_response/base_response.dart' as _i4;
import 'package:flower_app/app/feature/forget_password/data/model/reset_password_response.dart'
    as _i5;
import 'package:flower_app/app/feature/forget_password/domain/request/reset_password_request.dart'
    as _i6;
import 'package:flower_app/app/feature/forget_password/domain/use_case/reset_password_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i2.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ResetPasswordResponse>> invoke(
    _i6.ResetPasswordRequest? resetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [resetPasswordRequest]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ResetPasswordResponse>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i5.ResetPasswordResponse>>(
                    this,
                    Invocation.method(#invoke, [resetPasswordRequest]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ResetPasswordResponse>>);
}
