// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/app/feature/signup/api/data_source_impls/signup_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/app/config/base_response/base_response.dart' as _i5;
import 'package:flower_app/app/feature/signup/api/api_client/api_client.dart'
    as _i2;
import 'package:flower_app/app/feature/signup/api/data_source_impls/signup_remote_data_source_impl.dart'
    as _i3;
import 'package:flower_app/app/feature/signup/data/models/signup_dto.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignupApiClient_0 extends _i1.SmartFake
    implements _i2.SignupApiClient {
  _FakeSignupApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignupRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignupRemoteDataSourceImpl extends _i1.Mock
    implements _i3.SignupRemoteDataSourceImpl {
  MockSignupRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SignupApiClient get signupApiClient =>
      (super.noSuchMethod(
            Invocation.getter(#signupApiClient),
            returnValue: _FakeSignupApiClient_0(
              this,
              Invocation.getter(#signupApiClient),
            ),
          )
          as _i2.SignupApiClient);

  @override
  set signupApiClient(_i2.SignupApiClient? _signupApiClient) =>
      super.noSuchMethod(
        Invocation.setter(#signupApiClient, _signupApiClient),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.BaseResponse<_i6.SignupDto>> register(
    String? gender,
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? rePassword,
    String? phone,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [
              gender,
              firstName,
              lastName,
              email,
              password,
              rePassword,
              phone,
            ]),
            returnValue: _i4.Future<_i5.BaseResponse<_i6.SignupDto>>.value(
              _i7.dummyValue<_i5.BaseResponse<_i6.SignupDto>>(
                this,
                Invocation.method(#register, [
                  gender,
                  firstName,
                  lastName,
                  email,
                  password,
                  rePassword,
                  phone,
                ]),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.SignupDto>>);
}
