// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/app/feature/product_details/data/repo/product_details_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/app/config/base_response/base_response.dart' as _i5;
import 'package:flower_app/app/feature/product_details/data/data_sources/product_details_remote_data_source_contract.dart'
    as _i2;
import 'package:flower_app/app/feature/product_details/data/repo/product_details_repo_impl.dart'
    as _i3;
import 'package:flower_app/app/feature/product_details/domain/models/product_details_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductDetailsRemoteDataSourceContract_0 extends _i1.SmartFake
    implements _i2.ProductDetailsRemoteDataSourceContract {
  _FakeProductDetailsRemoteDataSourceContract_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [ProductDetailsRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDetailsRepoImpl extends _i1.Mock
    implements _i3.ProductDetailsRepoImpl {
  MockProductDetailsRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductDetailsRemoteDataSourceContract
  get productDetailsRemoteDataSourceContract =>
      (super.noSuchMethod(
            Invocation.getter(#productDetailsRemoteDataSourceContract),
            returnValue: _FakeProductDetailsRemoteDataSourceContract_0(
              this,
              Invocation.getter(#productDetailsRemoteDataSourceContract),
            ),
          )
          as _i2.ProductDetailsRemoteDataSourceContract);

  @override
  set productDetailsRemoteDataSourceContract(
    _i2.ProductDetailsRemoteDataSourceContract? value,
  ) => super.noSuchMethod(
    Invocation.setter(#productDetailsRemoteDataSourceContract, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.BaseResponse<_i6.ProductDetailsModel>> getProductDetails(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDetails, [productId]),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.ProductDetailsModel>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.ProductDetailsModel>>(
                    this,
                    Invocation.method(#getProductDetails, [productId]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.ProductDetailsModel>>);
}
