// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/app/feature/forget_password/domain/use_case/forget_password_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/app/config/base_response/base_response.dart' as _i4;
import 'package:flower_app/app/feature/forget_password/data/model/forget_password_response.dart'
    as _i5;
import 'package:flower_app/app/feature/forget_password/data/model/reset_password_response.dart'
    as _i10;
import 'package:flower_app/app/feature/forget_password/data/model/verify_otp_response.dart'
    as _i8;
import 'package:flower_app/app/feature/forget_password/domain/forget_password_repo_contract.dart'
    as _i2;
import 'package:flower_app/app/feature/forget_password/domain/request/forget_password_request.dart'
    as _i6;
import 'package:flower_app/app/feature/forget_password/domain/request/reset_password_request.dart'
    as _i11;
import 'package:flower_app/app/feature/forget_password/domain/request/verify_otp_request.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ForgetPasswordRepoContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordRepoContract extends _i1.Mock
    implements _i2.ForgetPasswordRepoContract {
  MockForgetPasswordRepoContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.ForgetPasswordResponse>> forgetPassword(
    _i6.ForgetPasswordRequest? forgetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequest]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.ForgetPasswordResponse>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i5.ForgetPasswordResponse>>(
                    this,
                    Invocation.method(#forgetPassword, [forgetPasswordRequest]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.ForgetPasswordResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.VerifyOtpResponse>> verifyOtp(
    _i9.VerifyOtpRequest? otpRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [otpRequest]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i8.VerifyOtpResponse>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i8.VerifyOtpResponse>>(
                    this,
                    Invocation.method(#verifyOtp, [otpRequest]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.VerifyOtpResponse>>);

  @override
  _i3.Future<_i4.BaseResponse<_i10.ResetPasswordResponse>> resetPassword(
    _i11.ResetPasswordRequest? resetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequest]),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i10.ResetPasswordResponse>>.value(
                  _i7.dummyValue<_i4.BaseResponse<_i10.ResetPasswordResponse>>(
                    this,
                    Invocation.method(#resetPassword, [resetPasswordRequest]),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i10.ResetPasswordResponse>>);
}
