// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/app/feature/home/presentation/views/tabs/home_tab/domain/use_cases/home_tab_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/app/config/base_response/base_response.dart' as _i5;
import 'package:flower_app/app/feature/home/presentation/views/tabs/home_tab/data/datasources/remote/home_tab_remote_data_source_contract.dart'
    as _i2;
import 'package:flower_app/app/feature/home/presentation/views/tabs/home_tab/data/repos/home_tab_repo_impl.dart'
    as _i3;
import 'package:flower_app/app/feature/home/presentation/views/tabs/home_tab/domain/models/get_home_tab_response_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeTabRemoteDataSourceContract_0 extends _i1.SmartFake
    implements _i2.HomeTabRemoteDataSourceContract {
  _FakeHomeTabRemoteDataSourceContract_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [HomeTabRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeTabRepoImpl extends _i1.Mock implements _i3.HomeTabRepoImpl {
  MockHomeTabRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeTabRemoteDataSourceContract get homeTabRemoteDataSourceContract =>
      (super.noSuchMethod(
            Invocation.getter(#homeTabRemoteDataSourceContract),
            returnValue: _FakeHomeTabRemoteDataSourceContract_0(
              this,
              Invocation.getter(#homeTabRemoteDataSourceContract),
            ),
          )
          as _i2.HomeTabRemoteDataSourceContract);

  @override
  _i4.Future<_i5.BaseResponse<_i6.GetHomeTabResponseModel>>
  getHomeTabDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getHomeTabDetails, []),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.GetHomeTabResponseModel>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.GetHomeTabResponseModel>>(
                    this,
                    Invocation.method(#getHomeTabDetails, []),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.GetHomeTabResponseModel>>);
}
