// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/app/feature/forget_password/api/forget_password_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flower_app/app/feature/forget_password/api/forget_password_api_client.dart'
    as _i5;
import 'package:flower_app/app/feature/forget_password/data/model/forget_password_response.dart'
    as _i2;
import 'package:flower_app/app/feature/forget_password/data/model/reset_password_response.dart'
    as _i4;
import 'package:flower_app/app/feature/forget_password/data/model/verify_otp_response.dart'
    as _i3;
import 'package:flower_app/app/feature/forget_password/domain/request/forget_password_request.dart'
    as _i7;
import 'package:flower_app/app/feature/forget_password/domain/request/reset_password_request.dart'
    as _i9;
import 'package:flower_app/app/feature/forget_password/domain/request/verify_otp_request.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForgetPasswordResponse_0 extends _i1.SmartFake
    implements _i2.ForgetPasswordResponse {
  _FakeForgetPasswordResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyOtpResponse_1 extends _i1.SmartFake
    implements _i3.VerifyOtpResponse {
  _FakeVerifyOtpResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponse_2 extends _i1.SmartFake
    implements _i4.ResetPasswordResponse {
  _FakeResetPasswordResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgetPasswordApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordApiClient extends _i1.Mock
    implements _i5.ForgetPasswordApiClient {
  MockForgetPasswordApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ForgetPasswordResponse> forgetPassword(
    _i7.ForgetPasswordRequest? forgetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequest]),
            returnValue: _i6.Future<_i2.ForgetPasswordResponse>.value(
              _FakeForgetPasswordResponse_0(
                this,
                Invocation.method(#forgetPassword, [forgetPasswordRequest]),
              ),
            ),
          )
          as _i6.Future<_i2.ForgetPasswordResponse>);

  @override
  _i6.Future<_i3.VerifyOtpResponse> verifyOtp(
    _i8.VerifyOtpRequest? verifyOtpRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [verifyOtpRequest]),
            returnValue: _i6.Future<_i3.VerifyOtpResponse>.value(
              _FakeVerifyOtpResponse_1(
                this,
                Invocation.method(#verifyOtp, [verifyOtpRequest]),
              ),
            ),
          )
          as _i6.Future<_i3.VerifyOtpResponse>);

  @override
  _i6.Future<_i4.ResetPasswordResponse> resetPassword(
    _i9.ResetPasswordRequest? resetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequest]),
            returnValue: _i6.Future<_i4.ResetPasswordResponse>.value(
              _FakeResetPasswordResponse_2(
                this,
                Invocation.method(#resetPassword, [resetPasswordRequest]),
              ),
            ),
          )
          as _i6.Future<_i4.ResetPasswordResponse>);
}
