// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/app/feature/signup/data/repo/signup_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/app/config/base_response/base_response.dart' as _i5;
import 'package:flower_app/app/feature/signup/data/data_sources/signup_remote_data_source_contract.dart'
    as _i2;
import 'package:flower_app/app/feature/signup/data/repo/signup_repo_impl.dart'
    as _i3;
import 'package:flower_app/app/feature/signup/domain/models/signup_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignupRemoteDataSourceContract_0 extends _i1.SmartFake
    implements _i2.SignupRemoteDataSourceContract {
  _FakeSignupRemoteDataSourceContract_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [SignupRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignupRepoImpl extends _i1.Mock implements _i3.SignupRepoImpl {
  MockSignupRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SignupRemoteDataSourceContract get signupRemote =>
      (super.noSuchMethod(
            Invocation.getter(#signupRemote),
            returnValue: _FakeSignupRemoteDataSourceContract_0(
              this,
              Invocation.getter(#signupRemote),
            ),
          )
          as _i2.SignupRemoteDataSourceContract);

  @override
  set signupRemote(_i2.SignupRemoteDataSourceContract? value) =>
      super.noSuchMethod(
        Invocation.setter(#signupRemote, value),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.BaseResponse<_i6.SignupModel>> register(
    String? gender,
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? rePassword,
    String? phone,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [
              gender,
              firstName,
              lastName,
              email,
              password,
              rePassword,
              phone,
            ]),
            returnValue: _i4.Future<_i5.BaseResponse<_i6.SignupModel>>.value(
              _i7.dummyValue<_i5.BaseResponse<_i6.SignupModel>>(
                this,
                Invocation.method(#register, [
                  gender,
                  firstName,
                  lastName,
                  email,
                  password,
                  rePassword,
                  phone,
                ]),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.SignupModel>>);
}
