// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/app/feature/auth/data/repo/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/app/config/base_response/base_response.dart' as _i4;
import 'package:flower_app/app/config/local_storage_processes/domain/storage_data_source_contract.dart'
    as _i7;
import 'package:flower_app/app/feature/auth/data/datasource/remote/remote_datasource_contract.dart'
    as _i2;
import 'package:flower_app/app/feature/auth/data/model/auth_response.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRemoteDatasourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasourceContract extends _i1.Mock
    implements _i2.AuthRemoteDatasourceContract {
  MockAuthRemoteDatasourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.AuthDto>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.AuthDto>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.AuthDto>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.AuthDto>>);
}

/// A class which mocks [StorageDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageDataSourceContract extends _i1.Mock
    implements _i7.StorageDataSourceContract {
  MockStorageDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i4.BaseResponse<bool>> addToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#addToken, [token]),
            returnValue: _i3.Future<_i4.BaseResponse<bool>>.value(
              _i6.dummyValue<_i4.BaseResponse<bool>>(
                this,
                Invocation.method(#addToken, [token]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<bool>>);

  @override
  _i3.Future<_i4.BaseResponse<bool>> addRememberMe(bool? rememberMe) =>
      (super.noSuchMethod(
            Invocation.method(#addRememberMe, [rememberMe]),
            returnValue: _i3.Future<_i4.BaseResponse<bool>>.value(
              _i6.dummyValue<_i4.BaseResponse<bool>>(
                this,
                Invocation.method(#addRememberMe, [rememberMe]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<bool>>);

  @override
  _i3.Future<_i4.BaseResponse<bool>> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i3.Future<_i4.BaseResponse<bool>>.value(
              _i6.dummyValue<_i4.BaseResponse<bool>>(
                this,
                Invocation.method(#clearToken, []),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<bool>>);

  @override
  _i3.Future<_i4.BaseResponse<bool>> clearRememberMe() =>
      (super.noSuchMethod(
            Invocation.method(#clearRememberMe, []),
            returnValue: _i3.Future<_i4.BaseResponse<bool>>.value(
              _i6.dummyValue<_i4.BaseResponse<bool>>(
                this,
                Invocation.method(#clearRememberMe, []),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<bool>>);
}
