// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/app/feature/auth/domain/use_case/get_auth_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/app/config/base_response/base_response.dart' as _i4;
import 'package:flower_app/app/feature/auth/domain/model/auth_model.dart'
    as _i5;
import 'package:flower_app/app/feature/auth/domain/repo/auth_repo_contract.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepoContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepoContract extends _i1.Mock implements _i2.AuthRepoContract {
  MockAuthRepoContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> getAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.BaseResponse<_i5.AuthModel>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.AuthModel>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.AuthModel>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.AuthModel>>);
}
