// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/app/feature/home/presentation/views/tabs/home_tab/presentation/view_model/home_tab_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_app/app/config/base_response/base_response.dart' as _i5;
import 'package:flower_app/app/feature/home/presentation/views/tabs/home_tab/domain/models/get_home_tab_response_model.dart'
    as _i6;
import 'package:flower_app/app/feature/home/presentation/views/tabs/home_tab/domain/repos/home_tab_repo_contract.dart'
    as _i2;
import 'package:flower_app/app/feature/home/presentation/views/tabs/home_tab/domain/use_cases/home_tab_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeTabRepoContract_0 extends _i1.SmartFake
    implements _i2.HomeTabRepoContract {
  _FakeHomeTabRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeTabUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeTabUseCase extends _i1.Mock implements _i3.HomeTabUseCase {
  MockHomeTabUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeTabRepoContract get homeTabRepoContract =>
      (super.noSuchMethod(
            Invocation.getter(#homeTabRepoContract),
            returnValue: _FakeHomeTabRepoContract_0(
              this,
              Invocation.getter(#homeTabRepoContract),
            ),
          )
          as _i2.HomeTabRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<_i6.GetHomeTabResponseModel>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.BaseResponse<_i6.GetHomeTabResponseModel>>.value(
                  _i7.dummyValue<_i5.BaseResponse<_i6.GetHomeTabResponseModel>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.GetHomeTabResponseModel>>);
}
